/*
Copyright 2021  Simon Arlott

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// https://issues.jenkins.io/browse/JENKINS-42079
def self = library("uuid@${env.BRANCH_NAME}")
def Cron = self.uk.uuid.jenkins.pipeline.Cron
def Email = self.uk.uuid.jenkins.pipeline.Email

pipeline {
	agent none
	triggers {
		cron("${Cron.schedule(this)}")
	}
	stages {
		stage("Test") {
			steps {
				echo "Hello World!"
			}
		}
	}
	post {
		always {
			script {
				Email.send(this)
			}
		}
	}
}
