/*
Copyright 2021  Simon Arlott

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

def common = library(
	identifier: "uuid@main",
	retriever: modernSCM([
		$class: "GitSCMSource",
		remote: "https://github.com/nomis/jenkins-uuid.git",
		credentialsId: "09218456-3c5d-493e-be04-d951b1d560c9",
	])
).uk.uuid.jenkins.pipeline

pipeline {
	agent none
	triggers {
		cron("${common.Cron.schedule(this)}")
	}
	stages {
		stage("Test") {
			steps {
				echo "Hello, World!"
			}
		}
	}
	post {
		always {
			script {
				common.Email.send(this)
			}
		}
	}
}
